"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Gauge, Search, X } from "lucide-react";
import type { VehicleRecord } from "@/lib/types";

const money = (cents: number | null) => cents == null ? "Consulte" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(cents / 100);
const km = (value: number) => new Intl.NumberFormat("pt-BR").format(value) + " km";
const condition = { novo: "Novo", usado: "Seminovo", repasse: "Repasse" };

export function Showroom({ vehicles }: { vehicles: VehicleRecord[] }) {
  const [mode, setMode] = useState("all");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [selected, setSelected] = useState<VehicleRecord | null>(null);
  const [photo, setPhoto] = useState(0);
  const filtered = useMemo(() => vehicles.filter((vehicle) => (mode === "all" || (mode === "venda" ? vehicle.saleEnabled : vehicle.rentalEnabled)) && (category === "all" || vehicle.category === category) && `${vehicle.name} ${vehicle.version} ${vehicle.year}`.toLowerCase().includes(query.toLowerCase())), [vehicles, mode, category, query]);
  const open = (vehicle: VehicleRecord) => { setSelected(vehicle); setPhoto(0); };
  const images = selected?.images.length ? selected.images : ["/stock/logo-nowa.jpg"];

  return <section id="estoque" className="bg-[#f2f2f0] px-4 py-20 text-[#111216] md:px-12 md:py-28"><div className="mx-auto max-w-[1500px]">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#ff5a2a]">Estoque atualizado</p><h2 className="display-title mt-3 text-6xl font-black uppercase md:text-8xl">Encontre o carro certo</h2></div><p className="max-w-md text-zinc-600">Os veículos vendidos continuam visíveis com a identificação de indisponível.</p></div>
    {vehicles.some((vehicle) => vehicle.isPromotion && vehicle.status === "active") && <div className="mt-9 flex items-center gap-3 rounded-2xl bg-[#111216] px-5 py-4 text-white"><span className="rounded-full bg-[#ff5a2a] px-3 py-1 text-xs font-black uppercase">Ofertas</span><p className="m-0 text-sm text-zinc-300">Veículos selecionados com preço promocional por tempo limitado.</p></div>}
    <div className="mt-8 flex gap-2 overflow-x-auto pb-2">{[["all", "Todos"], ["venda", "Comprar"], ["aluguel", "Alugar"]].map(([value, label]) => <button key={value} onClick={() => setMode(value)} className={`whitespace-nowrap rounded-full border px-5 py-2.5 text-sm font-bold ${mode === value ? "border-[#111216] bg-[#111216] text-white" : "border-zinc-300"}`}>{label}</button>)}</div>
    <div className="mt-3 grid gap-2 md:grid-cols-[1fr_240px]"><label className="flex h-14 items-center gap-3 rounded-xl border border-zinc-300 bg-white px-4"><Search size={19} className="text-zinc-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full outline-none" placeholder="Busque por marca ou modelo" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} className="h-14 rounded-xl border border-zinc-300 bg-white px-4"><option value="all">Todas as categorias</option><option value="hatch">Hatch</option><option value="sedan">Sedan</option><option value="suv">SUV</option><option value="picape">Picape</option></select></div>
    <p className="my-5 text-sm text-zinc-500"><b className="text-zinc-900">{filtered.length}</b> veículos encontrados</p>
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((vehicle) => { const currentPrice = vehicle.isPromotion && vehicle.promotionalPrice ? vehicle.promotionalPrice : vehicle.salePrice; return <article key={vehicle.id} className={`group overflow-hidden rounded-[20px] border border-zinc-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${vehicle.status === "sold" ? "opacity-80" : ""}`}>
      <div className="relative aspect-[1.45] overflow-hidden bg-zinc-200"><Image src={vehicle.images[0] || "/stock/logo-nowa.jpg"} alt={`${vehicle.name} ${vehicle.year}`} fill className="object-cover transition duration-500 group-hover:scale-105" unoptimized={vehicle.images[0]?.startsWith("/api/")} /><div className="absolute left-3 top-3 flex flex-wrap gap-1.5"><span className="rounded-full bg-[#ff5a2a] px-3 py-1.5 text-[11px] font-black uppercase text-white">{condition[vehicle.condition]}</span>{vehicle.isPromotion && vehicle.status === "active" && <span className="rounded-full bg-[#111216] px-3 py-1.5 text-[11px] font-black uppercase text-white">Promoção</span>}</div>{vehicle.status === "sold" && <div className="absolute inset-0 grid place-items-center bg-black/55"><span className="-rotate-6 border-4 border-white px-6 py-2 text-3xl font-black uppercase text-white">Vendido</span></div>}</div>
      <div className="p-5"><div className="flex justify-between gap-4"><div><h3 className="font-bold">{vehicle.name}</h3><p className="mt-1 text-sm text-zinc-500">{vehicle.version}</p></div><b>{vehicle.year}</b></div><div className="mt-5 flex gap-4 border-y border-zinc-100 py-3 text-xs text-zinc-600"><span className="flex items-center gap-1.5"><Gauge size={15} />{km(vehicle.mileage)}</span><span>{vehicle.transmission}</span><span>{vehicle.fuel}</span></div><div className="mt-5 flex items-end justify-between gap-4"><div><small className="block uppercase tracking-wider text-zinc-400">{vehicle.rentalEnabled && !vehicle.saleEnabled ? "Diária" : "Preço"}</small>{vehicle.isPromotion && vehicle.promotionalPrice && <span className="mr-2 text-sm text-zinc-400 line-through">{money(vehicle.salePrice)}</span>}<strong className="display-title text-2xl">{vehicle.rentalEnabled && !vehicle.saleEnabled ? money(vehicle.rentalPrice) : money(currentPrice)}</strong></div><button onClick={() => open(vehicle)} className="rounded-full bg-[#111216] px-4 py-2.5 text-sm font-bold text-white" disabled={vehicle.status === "sold"}>Detalhes</button></div></div>
    </article>; })}</div>
    {!filtered.length && <div className="rounded-2xl border border-dashed border-zinc-300 p-16 text-center"><h3 className="text-xl font-bold">Nenhum veículo encontrado</h3><p className="mt-2 text-zinc-500">Tente alterar os filtros da pesquisa.</p></div>}
  </div>

  {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-3 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="vehicle-title" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><div className="relative max-h-[94vh] w-full max-w-6xl overflow-auto rounded-[24px] bg-[#111318] text-white shadow-2xl md:grid md:grid-cols-[1.15fr_.85fr]">
    <button onClick={() => setSelected(null)} className="absolute right-3 top-3 z-20 grid h-11 w-11 place-items-center rounded-full bg-black/70" aria-label="Fechar"><X /></button>
    <div className="bg-black p-3"><div className="relative h-[46vh] min-h-[320px] overflow-hidden rounded-2xl md:h-[660px]"><Image src={images[photo]} alt={`${selected.name} — foto ${photo + 1}`} fill className="object-cover" unoptimized={images[photo].startsWith("/api/")} />{images.length > 1 && <><button onClick={() => setPhoto((photo - 1 + images.length) % images.length)} className="absolute left-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-black/60"><ChevronLeft /></button><button onClick={() => setPhoto((photo + 1) % images.length)} className="absolute right-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-black/60"><ChevronRight /></button></>}<span className="absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full bg-black/60 px-3 py-1 text-xs">{photo + 1} / {images.length}</span></div></div>
    <div className="p-6 md:p-10"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#ff5a2a] px-3 py-1 text-xs font-black uppercase">{condition[selected.condition]}</span>{selected.saleEnabled && <span className="rounded-full bg-white/10 px-3 py-1 text-xs">Venda</span>}{selected.rentalEnabled && <span className="rounded-full bg-white/10 px-3 py-1 text-xs">Locação</span>}</div><h2 id="vehicle-title" className="display-title mt-5 text-5xl font-black uppercase leading-none">{selected.name}</h2><p className="mt-2 text-zinc-400">{selected.version} · {selected.year}</p><div className="mt-7 border-y border-white/10 py-5"><span className="block text-xs uppercase tracking-wider text-zinc-500">Valor</span>{selected.isPromotion && selected.promotionalPrice && <span className="mr-3 text-zinc-500 line-through">{money(selected.salePrice)}</span>}<strong className="display-title text-4xl text-[#ff5a2a]">{money(selected.isPromotion ? selected.promotionalPrice : selected.salePrice)}</strong>{selected.rentalEnabled && <p className="mt-1 text-sm text-zinc-400">Locação a partir de {money(selected.rentalPrice)} / dia</p>}</div><div className="mt-6 grid grid-cols-2 gap-px overflow-hidden rounded-xl bg-white/10"><Spec label="Quilometragem" value={km(selected.mileage)} /><Spec label="Câmbio" value={selected.transmission} /><Spec label="Combustível" value={selected.fuel} /><Spec label="Categoria" value={selected.category} /></div><p className="mt-7 text-sm leading-6 text-zinc-300">{selected.description}</p><ul className="mt-5 grid grid-cols-2 gap-2 text-sm text-zinc-300">{selected.features.map((feature) => <li key={feature}>• {feature}</li>)}</ul><a className="mt-8 flex justify-center rounded-full bg-[#ff5a2a] px-6 py-3.5 font-bold" href={`https://wa.me/5546999194348?text=${encodeURIComponent(`Olá, vi o ${selected.name} ${selected.version} ${selected.year} no site e quero mais informações.`)}`} target="_blank" rel="noreferrer">Tenho interesse</a></div>
  </div></div>}
  </section>;
}

function Spec({ label, value }: { label: string; value: string }) { return <div className="bg-[#17191f] p-4"><small className="block text-[11px] uppercase tracking-wider text-zinc-500">{label}</small><b className="mt-1 block text-sm capitalize">{value}</b></div>; }
